server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/tb_vigilancia
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC
     

  sql:
    init:
      mode: never

  web:
    resources:
      cache:
        period: 365d
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: "/**"

security:
  jwt:
    issuer: tb.vc
    secret: ${JWT_SECRET:change_me_super_long_32_chars_min_2025_xxxxxxxxxxxxx}
    access-minutes: 60
    refresh-days: 7


app:
  cookie:
    secure: true          # Devtunnels/HTTPS => true; mismo origen local podría ser false
    same-site: none       # para front en otro origen/puerto (Vite 5173, devtunnels, etc.)


# Orígenes que pueden enviar/recibir cookies (CORS con credenciales)
cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000,https://6pjm529l-5173.brs.devtunnels.ms"

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: INFO
